security:
    acl:
        connection: default

    role_hierarchy:
        ROLE_MODERATOR:   [ROLE_USER]
        ROLE_ADMIN:       [ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: user, roles: [ 'ROLE_USER' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
                    superadmin: { password: superadmin, roles: [ 'ROLE_SUPER_ADMIN' ] }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        main:
            pattern: ^/
            anonymous: true
            provider:  in_memory
            form_login:
                login_path: security_login
                check_path: security_login_check
            logout:
                path:   security_logout
                target: security_login

    access_control:
        - { path: ^/(_(profiler|wdt)|css|images|js)/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_REMEMBERED }
