park_homepage:
    path:     /hello/{name}
    defaults: { _controller: ParkBundle:Default:index }

park_tutu:
    path:     /tutu/{name}
    defaults: { _controller: ParkBundle:Default:tutu }
    requirements:
        name:    "[a-zA-Z]+"

park_computer:
    path:     /park/computer
    defaults: { _controller: ParkBundle:Computer:computer }